=== Amedeo123/CEINMS/TestCfg/emgGenerator.xsd
<!--
     Author(s): Claudio Pizzolato - October 2013       
         email:  claudio.pizzolato@griffithuni.edu.au   
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="StringListType">
	<xs:list itemType="xs:string"/>
  </xs:simpleType>
  
  <xs:complexType name="EmgType">
	<xs:simpleContent>
		<xs:extension base="xs:string">
		  <xs:attribute type="xs:string" name="id" use="optional"/>
		  <xs:attribute type="xs:string" name="operation" use="optional"/>
		</xs:extension>
	 </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="EmgListType">
    <xs:sequence>
	  <xs:element name="emg" maxOccurs="unbounded" minOccurs="0" type="EmgType"/>	
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="emgGenerator">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="experimental" minOccurs="1" type="EmgListType"/>
        <xs:element name="mapping" minOccurs="1" type="EmgListType"/> 
        <xs:element type="StringListType" maxOccurs="1" name="output"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Amedeo123/CEINMS/TestCfg/emgGenerator.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<emgGenerator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emgGenerator.xsd">
<experimental>
	<emg id="emgId1"/>
	<emg id="emgId2"/>
	<emg id="emgId3"/>
	<emg id="emgId4"/>
	<emg id="emgId5"/>
	<emg id="emgId6"/>
	<emg id="emgId7"/>
</experimental>

<mapping>
	<emg id="emgId8"
		 operation="sum">
		 emgId1
		 emgId2
	</emg>

	<emg id="emgId9"
		 operation="mean">
		 emgId1
		 emgId2
	</emg>

	<emg id="emgId10"
		 operation="assign">
		 emgId2
	</emg>

	<emg id="emgId11"
		 operation="nil"/>
 </mapping>
 
<output>
	emgId1 emgId2 emgId3 emgId4 emgId5 emgId6 emgId7 emgId8 emgId9 emgId10 emgId11
</output>
</emgGenerator>

=== Amedeo123/CEINMS/TestCfg/emgGenerator/emgGenerator-16To34.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<emgGenerator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/emgGenerator.xsd">

<experimental>
	<emg id="addmag_r"/>
	<emg id="bicfemlh_r"/>
	<emg id="gaslat_r"/>
	<emg id="gasmed_r"/>
	<emg id="gmax_r"/>
	<emg id="gmed_r"/>
	<emg id="gra_r"/>
	<emg id="perlong_r"/>
	<emg id="recfem_r"/>
	<emg id="sar_r"/>
	<emg id="semimem_r"/>
	<emg id="sol_r"/>
	<emg id="tfl_r"/>
	<emg id="tibant_r"/>
	<emg id="vaslat_r"/>
	<emg id="vasmed_r"/>
</experimental>

<mapping>
	<emg id="addbrev_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="addlong_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="addmag1_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="addmag2_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="addmag3_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="bicfemsh_r"
		 operation="assign">
         bicfemlh_r
	</emg>
	
    <emg id="gmax1_r"
		 operation="assign">
         gmax_r
	</emg>
    <emg id="gmax2_r"
		 operation="assign">
         gmax_r
	</emg>
    <emg id="gmax3_r"
		 operation="assign">
         gmax_r
	</emg>

    <emg id="gmed1_r"
		 operation="assign">
         gmed_r
	</emg>
    <emg id="gmed2_r"
		 operation="assign">
         gmed_r
	</emg>
    <emg id="gmed3_r"
		 operation="assign">
         gmed_r
	</emg>

    <emg id="gmin1_r"
		 operation="mean">
         gmed_r
         gmax_r
	</emg>
    <emg id="gmin2_r"
		 operation="mean">
         gmed_r
         gmax_r
	</emg>
    <emg id="gmin3_r"
		 operation="mean">
         gmed_r
         gmax_r
	</emg>

	<emg id="illiacus_r"
		 operation="nil"/>

	<emg id="perbrev_r"
		 operation="assign">
         perlong_r
	</emg>
	<emg id="perter_r"
		 operation="assign">
         perlong_r
	</emg>

	<emg id="psoas_r"
		 operation="nil"/>

	<emg id="semiten_r"
		 operation="assign">
         semimem_r
	</emg>

    <emg id="vasint_r"
		 operation="mean">
         vaslat_r
         vasmed_r
	</emg>

 </mapping>
 
<output>
	addbrev_r addlong_r addmag1_r addmag2_r addmag3_r 
    bicfemlh_r bicfemsh_r 
    gaslat_r gasmed_r 
    gmax1_r gmax2_r gmax3_r 
    gmed1_r gmed2_r gmed3_r 
    gmin1_r gmin2_r gmin3_r 
    gra_r 
    illiacus_r 
    perbrev_r perlong_r perter_r
    psoas_r recfem_r sar_r
    semimem_r semiten_r sol_r
    tfl_r tibant_r
    vasint_r vaslat_r vasmed_r
</output>
</emgGenerator>

=== Amedeo123/CEINMS/TestCfg/emgGenerator/emgGenerator16To34Saxby.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<emgGenerator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../XSD/emgGenerator.xsd">

<experimental>
	<emg id="addmag_r"/>
	<emg id="bicfemlh_r"/>
	<emg id="gaslat_r"/>
	<emg id="gasmed_r"/>
	<emg id="gmax_r"/>
	<emg id="gmed_r"/>
	<emg id="gra_r"/>
	<emg id="perlong_r"/>
	<emg id="recfem_r"/>
	<emg id="sar_r"/>
	<emg id="semimem_r"/>
	<emg id="sol_r"/>
	<emg id="tfl_r"/>
	<emg id="tibant_r"/>
	<emg id="vaslat_r"/>
	<emg id="vasmed_r"/>
</experimental>

<mapping>
	<emg id="add_brev_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="add_long_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="add_mag1_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="add_mag2_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="add_mag3_r"
		 operation="assign">
         addmag_r
	</emg>
	<emg id="bifemsh_r"
		 operation="assign">
         bicfemlh_r
	</emg>
	<emg id="bifemlh_r"
		 operation="assign">
         bicfemlh_r
	</emg>
	
    <emg id="glut_max1_r"
		 operation="assign">
         gmax_r
	</emg>
    <emg id="glut_max2_r"
		 operation="assign">
         gmax_r
	</emg>
    <emg id="glut_max3_r"
		 operation="assign">
         gmax_r
	</emg>

    <emg id="glut_med1_r"
		 operation="assign">
         gmed_r
	</emg>
    <emg id="glut_med2_r"
		 operation="assign">
         gmed_r
	</emg>
    <emg id="glut_med3_r"
		 operation="assign">
         gmed_r
	</emg>

    <emg id="glut_min1_r"
		 operation="mean">
         gmed_r
         gmax_r
	</emg>
    <emg id="glut_min2_r"
		 operation="mean">
         gmed_r
         gmax_r
	</emg>
    <emg id="glut_min3_r"
		 operation="mean">
         gmed_r
         gmax_r
	</emg>

	<emg id="grac_r"
		 operation="assign">
		 gra_r
	</emg>
		 
	<emg id="iliacus_r"
		 operation="nil"/>
		 
	<emg id="med_gas_r"
		 operation="assign">
		 gasmed_r
	</emg>	
	<emg id="lat_gas_r"
		 operation="assign">
		 gaslat_r
	</emg>

	
	<emg id="per_brev_r"
		 operation="assign">
         perlong_r
	</emg>
	<emg id="per_long_r"
		 operation="assign">
         perlong_r
	</emg>
	<emg id="per_tert_r"
		 operation="assign">
         perlong_r
	</emg>

	<emg id="psoas_r"
		 operation="nil"/>

	<emg id="rect_fem_r"
		 operation="assign">
         recfem_r
	</emg>
	
	
	<emg id="semiten_r"
		 operation="assign">
         semimem_r
	</emg>

	<emg id="soleus_r"
		 operation="assign">
         sol_r
	</emg>
	
	<emg id="tib_ant_r"
		 operation="assign">
         tibant_r
	</emg>
    
	<emg id="vas_int_r"
		 operation="mean">
         vaslat_r
         vasmed_r
	</emg>
	<emg id="vas_lat_r"
		 operation="assign">
         vaslat_r
	</emg>
	<emg id="vas_med_r"
		 operation="assign">
         vasmed_r
	</emg>
 </mapping>
 
<output>
	add_brev_r add_long_r add_mag1_r add_mag2_r add_mag3_r 
    bifemlh_r bifemsh_r 
    glut_max1_r glut_max2_r glut_max3_r 
    glut_med1_r glut_med2_r glut_med3_r 
    glut_min1_r glut_min2_r glut_min3_r 
    grac_r 
    iliacus_r 
	lat_gas_r med_gas_r 
    per_brev_r per_long_r per_tert_r
    psoas_r rect_fem_r sar_r
    semimem_r semiten_r soleus_r
    tfl_r tib_ant_r
    vas_int_r vas_lat_r vas_med_r
</output>
</emgGenerator>
