=== Amedeo123/CEINMS/TestCfg/simulatedAnnealing.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      Parameters for Simulated Annealing.
      Copyright 2010 (C) Monica Reggiani. All rights reserved.
    </xs:documentation>
  </xs:annotation>
  
  <xs:complexType name = "SimulatedAnnealingType">
    <xs:sequence>
      <xs:element name = "noEpsilon" type= "xs:int"/>
      <xs:element name = "rt" type = "xs:double" />
      <xs:element name = "T" type = "xs:double" />
      <xs:element name = "NS" type = "xs:int" />
      <xs:element name = "NT" type = "xs:int" />
      <xs:element name = "epsilon" type = "xs:double"/>
      <xs:element name = "maxNoEval" type = "xs:int" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name = "simulatedAnnealing" type="SimulatedAnnealingType"/>
  
</xs:schema>

=== Amedeo123/CEINMS/TestCfg/simulatedAnnealing.xml
<?xml version="1.0"?>

<simulatedAnnealing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="simulatedAnnealing.xsd">
<noEpsilon>4</noEpsilon>
<rt>0.3</rt>
<T>20</T>
<NS>15</NS>
<NT>5</NT>
<epsilon>1.E-3</epsilon>
<maxNoEval>3000000</maxNoEval>
</simulatedAnnealing>
